kafka:
  hostname: kafka01
  image: antlypls/kafka:0.10.0.1
  environment:
    - KAFKA=localhost:9092
    - ZOOKEEPER=localhost:2181
  expose:
    - "2181"
  ports:
    - "9092:9092"

spark:
  image: antlypls/spark:1.6.2
  command: bash
  volumes:
    - ./target/scala-2.10:/app
  links:
   - kafka
